apiVersion: v1
kind: Namespace
metadata:
  name: healthcheck
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck
  namespace: healthcheck
spec:
  selector:
    matchLabels:
      app: healthcheck
  template:
    metadata:
      labels:
        app: healthcheck
    spec:
      containers:
      - name: healthcheck
        image: ghcr.io/toof-jp/healthcheck:sha-7ba6f32
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: healthcheck-configmap
              key: message
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcheck-configmap
  namespace: healthcheck
data:
  message: "hello, world"
